version: '3'

services:
  podcast-db:
    build: ./Database/.
    ports:
    - '27017:27017'
    volumes:
      - ./Database/DB-Data:/data
  podcast-python:
    build: ./Python/.
    ports:
    - "8346:8346"
    links:
    - podcast-db
    command: tail -F anything
  podcast-backend:
    build: ./Backend/.
    ports:
    - "8347:8347"
    command: tail -F anything
  podcast-frontend:
    build: ./Frontend/.
    ports:
    - "8348:8348"
    links:
    - podcast-backend
    command: tail -F anything